"""cos — pull-based chief-of-staff reports.

Design rules, deliberately enforced here rather than assumed:
  * pull, not push — you run it; nothing is scheduled and nothing is delivered
  * allowed to be empty — a report that is sometimes empty is believed
  * read-only — the Gmail mirror and the vault are never written to
  * no model — every number is derived from mail headers by rule
"""

from __future__ import annotations

import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import click
from rich import box
from rich.console import Console
from rich.table import Table

from . import __version__, compat
from .config import Config
from .export_brain import export
from .contacts import (
    attach_recent_subjects,
    corpus_freshness,
    load_ledger,
    utc_now,
    window_start,
)
from .backend import open_backend
from .kuzu import KuzuClient, KuzuError
from .reports import deal_status, owed_replies
from . import today as today_page
from . import dashboard as dashboard_page
from . import notes as notes_store
from .vault import attach_domains, load_deal_domains, load_deals, load_internal_domains

console = Console(width=100)


def _fmt_days(days: int | None) -> str:
    """Compact and fixed-width, so the column never collapses."""
    if days is None:
        return "  —"
    if days == 0:
        return "today"
    return f"{days}d"


def _plain_table(title: str) -> Table:
    """Borderless table — reads as a list, not a spreadsheet."""
    return Table(
        title=title,
        title_style="bold",
        title_justify="left",
        header_style="dim",
        box=box.SIMPLE_HEAD,
        pad_edge=False,
        show_edge=False,
    )


def _severity(days: int | None, threshold: int) -> str:
    if days is None:
        return "dim"
    if days >= threshold * 3:
        return "bold red"
    if days >= threshold:
        return "yellow"
    return "green"


def _truncate(text: str, width: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= width else text[: width - 1] + "…"


def _build(cfg: Config, client: KuzuClient, now: datetime):
    ledger = load_ledger(client, cfg.principal_addresses)
    attach_recent_subjects(
        client, ledger, cfg.principal_addresses, window_start(now, cfg.owed_window_days)
    )
    return ledger




SOUL_BEGIN = "<!-- cos:begin DATE -->"
SOUL_END = "<!-- cos:end DATE -->"
# The block already sitting in an existing SOUL.md carries the pre-rename
# marker. Matching only the current spelling would find no block, append a
# second one, and leave the old date above it — so the agent would load two
# contradictory "Today is" lines, with the stale one first. That is precisely
# the failure this whole mechanism exists to prevent.
_SOUL_BLOCK_RE = re.compile(
    rf"<!--\s*(?:cos|{compat.LEGACY_DIRNAME}):begin\s+DATE\s*-->"
    rf".*?"
    rf"<!--\s*(?:cos|{compat.LEGACY_DIRNAME}):end\s+DATE\s*-->",
    re.DOTALL,
)


def _stamp_soul_date(now, upcoming) -> bool:
    """Write today's date into the agent's system prompt.

    Kiran kept answering "what do I have tomorrow" from a two-month-old email
    whose subject read "meeting tomorrow". Retrieval can always lose to a better
    lexical match, so the date must not depend on retrieval at all — SOUL.md is
    loaded as the agent identity, ahead of any search, and cannot be outvoted.

    Managed block only: everything Wei wrote in SOUL.md is preserved.
    """
    soul = Path.home() / ".hermes" / "SOUL.md"
    if not soul.exists():
        return False
    local = now.astimezone()
    lines = [
        SOUL_BEGIN,
        f"**Today is {local:%A %d %B %Y} ({local:%Y-%m-%d}).** This line is "
        f"regenerated by `cos brief`; trust it over any date you infer from a "
        f"document, and never take a date from an email subject as \"today\".",
    ]
    if upcoming:
        today = [e for e in upcoming if e.start.astimezone().date() == local.date()]
        tmrw = [e for e in upcoming
                if (e.start.astimezone().date() - local.date()).days == 1]
        for label, group in (("Today", today), ("Tomorrow", tmrw)):
            if group:
                items = "; ".join(
                    f"{e.start.astimezone():%H:%M} {e.summary}"
                    + ("" if e.status == "confirmed" else f" [{e.status}]")
                    for e in group[:8]
                )
                lines.append(f"- **{label}:** {items}")
    lines.append(
        "Fuller detail, including attendees and who is waiting on a reply, is in "
        "`90_agent/today.md`."
    )
    lines.append(SOUL_END)
    block = "\n".join(lines)

    text = soul.read_text(encoding="utf-8")
    # Replace the first block and DELETE any others. Not just the first: the
    # rename briefly left two blocks in this file, an old-marker one above a
    # new-marker one, and a count=1 substitution would have refreshed the top
    # one forever while the stale copy sat below it permanently. Collapsing to
    # exactly one is the only state that cannot drift.
    seen = 0

    def _replace(_m: re.Match) -> str:
        nonlocal seen
        seen += 1
        return block if seen == 1 else ""

    text = _SOUL_BLOCK_RE.sub(_replace, text)
    if not seen:
        text = text.rstrip() + "\n\n" + block + "\n"
    # Collapse the blank lines a deleted duplicate leaves behind.
    text = re.sub(r"\n{3,}", "\n\n", text)
    soul.write_text(text, encoding="utf-8")
    return True


def _upcoming_meetings(cfg, now, days: int = 7, limit: int = 25):
    """The next week of meetings, or nothing if calendar is not connected.

    Deliberately best-effort: `cos brief` must still produce a date anchor on
    a machine with no Google grant, so a calendar failure degrades the page
    rather than the command.
    """
    try:
        from .calendar_source import load_events, is_worth_a_page
    except ImportError:
        return []
    try:
        principals = {p.lower() for p in cfg.principal_addresses}
        events = load_events(days_back=0, days_forward=days, now=now)
        upcoming = [
            e for e in events
            if e.start >= now and is_worth_a_page(e, principals)[0]
        ]
        upcoming.sort(key=lambda e: e.start)
        return upcoming[:limit]
    except Exception:
        return []


def _freshness_warning(client: KuzuClient, now: datetime) -> None:
    newest = corpus_freshness(client)
    if newest is None:
        return
    lag = (now - newest).days
    if lag > 2:
        console.print(
            f"[yellow]⚠ The mail graph's newest message is {lag} days old "
            f"({newest.astimezone():%Y-%m-%d}). Results are stale — check that mbsync "
            f"and the "
            f"scheduled Kuzu rebuild are running.[/yellow]\n"
        )


@click.group()
@click.version_option(__version__, prog_name="cos")
def main() -> None:
    """Chief-of-staff reports over the local Gmail mirror."""


def _require_setup() -> "Config":
    """Stop with directions instead of computing against defaults.

    On a machine with nothing configured, `cos brief` used to invent a
    ~/vault directory and write a file into it, against an empty principal.
    A first command on a fresh install should say what to do next, not
    guess.
    """
    cfg = Config.load()
    if not cfg.principal_addresses:
        console.print("[yellow]Not configured yet.[/yellow] Run "
                      "[bold]cos setup[/bold] — it lists each step and "
                      "checks it off as you go.")
        sys.exit(2)
    return cfg


@main.command()
def setup() -> None:
    """Where your install stands: every prerequisite, checked, with the fix.

    Safe to run at any time, from the first minute. Nothing here writes
    anything except .env (copied from the example, once, so there is a file
    to edit).
    """
    from pathlib import Path

    repo = Path(__file__).resolve().parents[2]
    env_file = repo / ".env"
    if not env_file.exists() and (repo / ".env.example").exists():
        env_file.write_text((repo / ".env.example").read_text())
        console.print(f"[green]✓[/green] created .env from .env.example — edit it next")

    cfg = Config.load()
    rows: list[tuple[bool, str, str]] = []

    rows.append((env_file.exists(), ".env exists",
                 "cp .env.example .env"))
    rows.append((bool(cfg.principal_addresses),
                 f"COS_PRINCIPAL_ADDRESSES set"
                 + (f" ({cfg.principal_addresses[0]})" if cfg.principal_addresses else ""),
                 "edit .env: your own email address(es), comma-separated"))

    oauth = Path.home() / ".config" / "cos" / "oauth_client.json"
    from .google_auth import TOKEN_FILE as GOOGLE_TOKEN
    from .ms_auth import TOKEN_FILE as MS_TOKEN
    has_google = GOOGLE_TOKEN.exists()
    has_ms = MS_TOKEN.exists()
    rows.append((oauth.exists() or has_google or has_ms,
                 "a mail connection is prepared",
                 "Gmail: save the OAuth client JSON to "
                 "~/.config/cos/oauth_client.json (README step 2). "
                 "Microsoft: see docs/SETUP-MICROSOFT.md"))
    rows.append((has_google or has_ms,
                 "signed in to mail ("
                 + ("Gmail" if has_google else "Microsoft" if has_ms else "none")
                 + ")",
                 "Gmail: cos check (first run opens the consent screen). "
                 "Microsoft: cos ms-auth"))

    rows.append((cfg.vault_root.is_dir(),
                 f"notes folder exists ({cfg.vault_root})",
                 "optional — set COS_VAULT_ROOT in .env to your Obsidian "
                 "vault, or leave unset to skip notes"))
    rows.append(((repo / "config" / "deal_domains.yaml").exists(),
                 "deal list exists (config/deal_domains.yaml)",
                 "optional — cp config/deal_domains.example.yaml "
                 "config/deal_domains.yaml and add your deals"))

    ok = True
    for good, label, fix in rows:
        mark = "[green]✓[/green]" if good else "[red]✗[/red]"
        console.print(f"{mark} {label}")
        if not good:
            ok = False
            console.print(f"    → {fix}")

    console.print()
    if ok:
        console.print("[green]Ready.[/green] Try: [bold]cos brief[/bold], "
                      "then [bold]cos owed[/bold]. Dashboard: cos serve. "
                      "Brain + assistant: docs/SETUP-gbrain-hermes.md")
    else:
        console.print("Fix the [red]✗[/red] lines top to bottom, then run "
                      "[bold]cos setup[/bold] again.")
        sys.exit(1)


@main.command()
def check() -> None:
    """Verify the graph is reachable and current."""
    cfg = Config.load()
    with open_backend(cfg) as client:
        if not client.health():
            if getattr(client, "is_gmail", False):
                console.print("[red]✗[/red] Gmail unreachable — run `cos google-auth`")
            else:
                console.print(f"[red]✗[/red] Kuzu server unreachable at {cfg.kuzu_url}")
                console.print(
                    "  Start it:  cd $COS_GMAIL_ROOT && python scripts/serve.py --port 7001"
                )
            sys.exit(1)
        newest = corpus_freshness(client)
        console.print(f"[green]✓[/green] Mail source: {client.describe()}"
                      if getattr(client, "is_gmail", False)
                      else f"[green]✓[/green] Kuzu reachable at {cfg.kuzu_url}")
        console.print(f"  Newest message: {newest.astimezone():%Y-%m-%d %H:%M %Z}" if newest else "  empty graph")
        console.print(f"  Principal: {', '.join(cfg.principal_addresses)}")
        console.print(f"  Vault: {cfg.vault_root}")
        deals = load_deals(cfg.vault_root)
        console.print(f"  Deals found in vault: {len(deals)}")


@main.command()
@click.option("--days", type=int, default=None, help="Quiet threshold in days.")
@click.option("--all", "show_all", is_flag=True, help="Include deals under threshold.")
def quiet(days: int | None, show_all: bool) -> None:
    """Named deals with no human contact recently."""
    cfg = _require_setup()
    threshold = days if days is not None else cfg.quiet_days
    now = utc_now()

    deals = load_deals(cfg.vault_root)
    if not deals:
        console.print(
            "[yellow]No deals found.[/yellow] Expected an '## At a glance' table in "
            f"{cfg.vault_root}/05_workspace/Task_management/Pipeline.md"
        )
        return
    attach_domains(deals, load_deal_domains(cfg.deal_domains_path))

    try:
        with open_backend(cfg) as client:
            _freshness_warning(client, now)
            statuses = deal_status(deals, _build(cfg, client, now), now)
    except KuzuError as exc:
        console.print(f"[red]{exc}[/red]")
        sys.exit(1)

    flagged = [s for s in statuses if s.mapped and (show_all or (s.days_quiet(now) or 0) >= threshold)]
    unmapped = [s for s in statuses if not s.mapped]

    if not flagged:
        console.print(
            f"[green]Nothing quiet.[/green] All {len(statuses) - len(unmapped)} mapped "
            f"deals had human contact within {threshold} days."
        )
    else:
        table = _plain_table(f"Deals quiet ≥ {threshold} days  ·  {now.astimezone():%Y-%m-%d}")
        table.add_column("Quiet", justify="right", no_wrap=True, min_width=6)
        table.add_column("Deal", no_wrap=True, min_width=22)
        table.add_column("Ball", no_wrap=True, min_width=6)
        table.add_column("Stated next step", no_wrap=True, min_width=38)
        for s in flagged:
            d = s.days_quiet(now)
            table.add_row(
                f"[{_severity(d, threshold)}]{_fmt_days(d)}[/]",
                _truncate(s.deal.name, 22),
                "[yellow]yours[/yellow]" if s.ball_in_our_court() else "[dim]theirs[/dim]",
                _truncate(s.deal.next_step or "—", 38),
            )
        console.print(table)

    if unmapped:
        console.print(
            f"\n[dim]{len(unmapped)} deal(s) have no email domain mapped and were not "
            f"checked: {', '.join(s.deal.name for s in unmapped)}.\n"
            f"Add them to config/deal_domains.yaml.[/dim]"
        )


@main.command()
@click.option("--days", type=int, default=None, help="Only mail newer than this.")
@click.option("--limit", type=int, default=25, help="Max rows.")
@click.option(
    "--include-new",
    is_flag=True,
    help="Also show people you have never written to (noisier).",
)
def owed(days: int | None, limit: int, include_new: bool) -> None:
    """People who wrote last and have had no reply from you."""
    cfg = _require_setup()
    window = days if days is not None else cfg.owed_window_days
    now = utc_now()

    try:
        with open_backend(cfg) as client:
            _freshness_warning(client, now)
            ledger = _build(cfg, client, now)
    except KuzuError as exc:
        console.print(f"[red]{exc}[/red]")
        sys.exit(1)

    internal = load_internal_domains(cfg.deal_domains_path)
    items = owed_replies(
        ledger,
        now,
        window,
        internal_domains=internal,
        require_prior_reply=not include_new,
    )

    if not items:
        console.print(
            f"[green]Inbox conscience clear.[/green] Nobody outside "
            f"{', '.join(sorted(internal)) or 'your org'} is waiting on you "
            f"within the last {window} days."
        )
        return

    table = _plain_table(f"Waiting on you  ·  {now.astimezone():%Y-%m-%d}")
    table.add_column("Wait", justify="right", no_wrap=True, min_width=5)
    table.add_column("Who", no_wrap=True, min_width=22)
    table.add_column("Org", no_wrap=True, min_width=20)
    table.add_column("Their last message", no_wrap=True, min_width=38)
    for item in items[:limit]:
        table.add_row(
            f"[{_severity(item.days_waiting, 7)}]{_fmt_days(item.days_waiting)}[/]",
            _truncate(item.who, 22),
            _truncate(item.counterparty.domain, 20),
            _truncate(item.subject, 38),
        )
    console.print(table)
    console.print(
        f"[dim]{len(items)} waiting; showing {min(limit, len(items))}. "
        f"Counterparty-level, not thread-level — see README.[/dim]"
    )


@main.command()
@click.option(
    "--path", type=click.Path(path_type=Path), default=None,
    help="Dashboard file (default: 05_workspace/Task_management/Dashboard.md).",
)
def dashboard(path: Path | None) -> None:
    """Update the dashboard, preserving everything you have written in it."""
    cfg = _require_setup()
    now = utc_now()
    target = path or (
        cfg.vault_root / "05_workspace" / "Task_management" / "Dashboard.md"
    )
    deals = load_deals(cfg.vault_root)
    attach_domains(deals, load_deal_domains(cfg.deal_domains_path))
    try:
        with open_backend(cfg) as client:
            _freshness_warning(client, now)
            ledger = _build(cfg, client, now)
    except KuzuError as exc:
        console.print(f"[red]{exc}[/red]")
        sys.exit(1)

    statuses = deal_status(deals, ledger, now)
    owed = owed_replies(
        ledger, now, cfg.owed_window_days,
        internal_domains=load_internal_domains(cfg.deal_domains_path),
    )
    existing = target.read_text(encoding="utf-8") if target.is_file() else None
    body, rescued = dashboard_page.render(now, statuses, owed, cfg.quiet_days, existing)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")

    # Index whatever the user has written, with the computed state at the time.
    ctx = {
        f"deal:{dashboard_page._slug(s.deal.name)}": {
            "quiet_days": s.days_quiet(now),
            "ball_with": "you" if s.ball_in_our_court() else "them",
            "stage": s.deal.stage,
        }
        for s in statuses
    }
    conn = notes_store.connect(cfg.notes_db)
    nstats = notes_store.sync(conn, notes_store.extract_from_dashboard(body), now, ctx)
    titles = {f"deal:{dashboard_page._slug(s.deal.name)}": s.deal.name for s in statuses}
    titles["journal"] = "General"
    # Link each notes page at the org card and any mapped domain, so gbrain's
    # graph-adjacency boost lifts a four-line page out of the shadow of the
    # thousand-word wiki pages it competes with.
    note_links: dict[str, list[str]] = {}
    for s_ in statuses:
        key = f"deal:{dashboard_page._slug(s_.deal.name)}"
        note_links[key] = [
            f"org-{dashboard_page._slug(d)}" for d in (s_.deal.domains or [])
        ]
    n_pages = notes_store.export_pages(
        conn, cfg.vault_root / "90_agent" / "Notes", titles, note_links,
    )

    console.print(f"[green]✓[/green] {target}")
    console.print(
        f"  {len([s for s in statuses if s.mapped])} deal(s) · {len(owed)} awaiting reply"
        + ("  [dim](created)[/dim]" if existing is None else "  [dim](updated in place)[/dim]")
    )
    if any(nstats[k] for k in ("new", "removed", "restored")):
        bits = [f"{nstats['new']} new" if nstats["new"] else "",
                f"{nstats['removed']} removed" if nstats["removed"] else "",
                f"{nstats['restored']} restored" if nstats["restored"] else ""]
        console.print(
            f"  [dim]notes: {', '.join(b for b in bits if b)} "
            f"({nstats['still_there'] + nstats['new']} tracked, "
            f"{n_pages} brain page(s))[/dim]"
        )
    if rescued:
        console.print(
            f"[yellow]  Moved your text out of {len(rescued)} computed block(s) "
            f"into the notes beneath: {', '.join(rescued)}[/yellow]"
        )


@main.command("note")
@click.argument("text", nargs=-1, required=True)
@click.option("--about", default=None, help="Entity, e.g. northwind, hillcrest, or a person.")
def note_cmd(text: tuple[str, ...], about: str | None) -> None:
    """Record something that exists nowhere else — a call, a hallway remark."""
    cfg = Config.load()
    now = utc_now()
    body = " ".join(text).strip()
    if not body:
        console.print("[red]Nothing to record.[/red]")
        sys.exit(1)

    entity = f"deal:{dashboard_page._slug(about)}" if about else "journal"

    # Markdown is the home; the DB is an index over it. Append first so a
    # database failure can never lose what you wrote.
    journal = cfg.vault_root / "05_workspace" / "Task_management" / "Kiran-Log.md"
    journal.parent.mkdir(parents=True, exist_ok=True)
    if not journal.exists():
        journal.write_text(
            "# Kiran Log\n\n> Things told to Kiran that are in no email and no "
            "note — calls, hallway remarks, judgement. Append-only; Kiran indexes "
            "it but never rewrites it.\n",
            encoding="utf-8",
        )
    with journal.open("a", encoding="utf-8") as fh:
        tag = f" · about **{about}**" if about else ""
        fh.write(f"\n## {now.astimezone():%Y-%m-%d %H:%M}{tag}\n\n- {body}\n")

    conn = notes_store.connect(cfg.notes_db)
    fresh = notes_store.add(conn, notes_store.Note(entity, body, source="cli"), now)
    notes_store.export_pages(conn, cfg.vault_root / "90_agent" / "Notes")
    console.print(
        f"[green]✓[/green] recorded{' about ' + about if about else ''} → {journal}"
        + ("" if fresh else "  [dim](already knew this one)[/dim]")
    )


@main.command("notes")
@click.option("--about", default=None, help="Filter by entity substring.")
@click.option("--all", "show_all", is_flag=True, help="Include notes you deleted.")
@click.option("--limit", type=int, default=30)
@click.option("--reindex", is_flag=True, help="Rebuild the index from the markdown.")
def notes_cmd(about: str | None, show_all: bool, limit: int, reindex: bool) -> None:
    """What you have told Kiran, and when."""
    cfg = Config.load()
    conn = notes_store.connect(cfg.notes_db)
    if reindex:
        tm = cfg.vault_root / "05_workspace" / "Task_management"
        dash = (tm / "Dashboard.md").read_text(encoding="utf-8") if (tm / "Dashboard.md").is_file() else ""
        log = (tm / "Kiran-Log.md").read_text(encoding="utf-8") if (tm / "Kiran-Log.md").is_file() else ""
        r = notes_store.reindex(conn, dash, log, utc_now())
        console.print(
            f"[green]✓[/green] rebuilt from markdown: {r['dashboard']} from Dashboard.md, "
            f"{r['log']} from Kiran-Log.md"
        )
    rows = notes_store.query(conn, about, include_removed=show_all, limit=limit)
    if not rows:
        console.print("[yellow]No notes recorded yet.[/yellow]  Try: cos note --about hillcrest \"...\"")
        return
    table = _plain_table(f"Notes{f' · {about}' if about else ''}")
    table.add_column("Written", no_wrap=True, min_width=10)
    table.add_column("About", no_wrap=True, min_width=16)
    table.add_column("Note", no_wrap=True, min_width=46)
    table.add_column("At the time", no_wrap=True, min_width=14)
    for r in rows:
        ctx = ""
        if r["context"]:
            try:
                import json as _j
                d = _j.loads(r["context"]) or {}
                if d.get("quiet_days") is not None:
                    ctx = f"quiet {d['quiet_days']}d, ball {d.get('ball_with','?')}"
            except Exception:
                pass
        label = r["entity"].replace("deal:", "")
        text = _truncate(r["text"], 46)
        if r["removed_at"]:
            text = f"[dim strike]{text}[/]"
        table.add_row(r["first_seen"][:10], _truncate(label, 16), text, ctx)
    console.print(table)
    s = notes_store.stats(conn)
    console.print(
        f"[dim]{s.get('live') or 0} live, {s.get('removed') or 0} deleted, "
        f"across {s.get('entities') or 0} entities since {(s.get('earliest') or '')[:10]}[/dim]"
    )


@main.command()
def brief() -> None:
    """Write 90_agent/today.md — the date anchor plus exhaustive lists."""
    cfg = _require_setup()
    now = utc_now()
    deals = load_deals(cfg.vault_root)
    attach_domains(deals, load_deal_domains(cfg.deal_domains_path))
    try:
        with open_backend(cfg) as client:
            _freshness_warning(client, now)
            ledger = _build(cfg, client, now)
    except KuzuError as exc:
        console.print(f"[red]{exc}[/red]")
        sys.exit(1)

    statuses = deal_status(deals, ledger, now)
    owed = owed_replies(
        ledger, now, cfg.owed_window_days,
        internal_domains=load_internal_domains(cfg.deal_domains_path),
    )
    _brief_upcoming = _upcoming_meetings(cfg, now)
    _stamp_soul_date(now, _brief_upcoming)
    path = today_page.write(
        cfg.vault_root / "90_agent" / "today.md",
        today_page.render(
            now, statuses, owed, cfg.quiet_days, cfg.owed_window_days,
            upcoming=_brief_upcoming,
        ),
    )
    quiet_n = len([s for s in statuses if s.mapped and (s.days_quiet(now) or 0) >= cfg.quiet_days])
    console.print(
        f"[green]✓[/green] {path}\n"
        f"  date anchor {now.astimezone():%Y-%m-%d} · {quiet_n} quiet deal(s) · "
        f"{len(owed)} awaiting your reply"
    )


@main.command("export-brain")
@click.option("--since", default="2025-08-01", help="Only threads active since this date.")
@click.option(
    "--out",
    type=click.Path(path_type=Path),
    default=Path.home() / "brain" / "email",
    help="Directory to write thread pages into.",
)
@click.option("--limit", type=int, default=None, help="Stop after N pages (for a trial run).")
@click.option("--dry-run", is_flag=True, help="Report what would be written, write nothing.")
def export_brain(since: str, out: Path, limit: int | None, dry_run: bool) -> None:
    """Write email threads into the brain as markdown pages."""
    cfg = Config.load()
    try:
        start = datetime.fromisoformat(since).replace(tzinfo=timezone.utc)
    except ValueError:
        console.print(f"[red]--since must be ISO date (YYYY-MM-DD), got {since!r}[/red]")
        sys.exit(1)

    target = Path(tempfile.mkdtemp(prefix="cos-dry-")) if dry_run else out
    try:
        with open_backend(cfg) as client:
            console.print(f"Loading threads since {start:%Y-%m-%d}…")
            stats = export(
                client, cfg.principal_addresses, start, target,
                cfg.gmail_root, cfg.vault_root,
                cfg.vault_root / "90_agent",
                load_ledger(client, cfg.principal_addresses),
                load_deal_domains(cfg.deal_domains_path),
                load_internal_domains(cfg.deal_domains_path), limit,
            )
    except KuzuError as exc:
        console.print(f"[red]{exc}[/red]")
        sys.exit(1)

    console.print(
        f"\n[bold]{stats.pages_written}[/bold] page(s) "
        f"{'would be written' if dry_run else 'written'} from "
        f"{stats.threads_seen} thread(s)"
        + ("" if dry_run else f" → {target}")
    )
    if stats.cards_written:
        console.print(
            f"[bold]{stats.people_cards}[/bold] person + [bold]{stats.org_cards}[/bold] org "
            f"card(s) → {cfg.vault_root}/90_agent  "
            f"({stats.card_links} linked to a 10_wiki page)"
        )
    if stats.resolution:
        r = stats.resolution
        total = sum(r.values())
        pct = (100 * (r["by_address"] + r["by_name"]) / total) if total else 0
        console.print(
            f"\n[dim]People links: {r['by_address']} by address claim, "
            f"{r['by_name']} by exact unique name, {r['unresolved']} unresolved "
            f"({pct:.0f}% linked)[/dim]"
        )
        if stats.conflicts:
            console.print(
                f"[yellow]{len(stats.conflicts)} address(es) claimed by two People "
                f"pages — left unlinked rather than guessed:[/yellow]"
            )
            for a, owners in list(stats.conflicts.items())[:6]:
                console.print(f"  [yellow]{a} → {', '.join(owners)}[/yellow]")
    if stats.skipped:
        console.print("\n[dim]Skipped:[/dim]")
        for reason, n in sorted(stats.skipped.items(), key=lambda kv: -kv[1]):
            console.print(f"  [dim]{n:6d}  {reason}[/dim]")
    if not dry_run and stats.pages_written:
        console.print(
            "\n[dim]Next: commit them and let gbrain pick them up —\n"
            "  cd ~/brain && git add -A && git commit -qm 'email import'\n"
            "  gbrain sync && gbrain extract --stale && gbrain embed --stale[/dim]"
        )


if __name__ == "__main__":
    main()

@main.command("capture")
@click.option("--dry-run", is_flag=True, help="Show what would be kept, write nothing.")
@click.option("--session", default=None, help="Limit to one session id.")
def capture_cmd(dry_run: bool, session: str | None) -> None:
    """Save durable things you told Kiran in chat into the log.

    Run before resetting a conversation. Everything worth keeping becomes a
    dated note; the chat itself then costs nothing to discard.
    """
    from . import capture as capture_mod

    cfg = Config.load()
    now = utc_now()
    try:
        facts = capture_mod.capture(cfg, now, session_id=session, dry_run=dry_run)
    except Exception as exc:
        console.print(f"[red]✗[/red] capture failed: {type(exc).__name__}: {exc}")
        sys.exit(1)

    if not facts:
        console.print("[dim]Nothing new worth keeping.[/dim]")
        return
    verb = "would keep" if dry_run else "recorded"
    console.print(f"[green]✓[/green] {verb} {len(facts)} thing(s):")
    for f in facts:
        about = f" [dim]({f.about})[/dim]" if f.about else ""
        console.print(f"  · {f.text}{about}")


@main.command("review")
@click.option("--hours", default=24, help="How far back to look.")
@click.option("--fix", is_flag=True, help="Apply the mechanical fixes.")
def review_cmd(hours: int, fix: bool) -> None:
    """What is going wrong with Kiran, from its own conversations.

    Mechanical problems (a hung run, a dead gateway) can be fixed with --fix.
    Anything needing judgement is reported, never applied — a loop that edits
    its own instructions from a guessed diagnosis makes things worse.
    """
    from . import review as review_mod

    rev = review_mod.run(hours=hours)
    fixed = review_mod.remediate(rev) if fix else []
    console.print(review_mod.render(rev, fixed))
    if rev.judgement and not fix:
        console.print("[dim]Run with --fix to apply the mechanical fixes.[/dim]")


@main.command("health")
@click.option("--quiet", "quiet_", is_flag=True,
              help="Print nothing when everything passes; exit 0/1 only.")
def health_cmd(quiet_: bool) -> None:
    """Is the pipeline actually working?

    `review` watches what the agent said. This watches whether the machinery
    under it ran. Every check asserts positive evidence with a freshness bound,
    because every failure this system has had looked like success — the vault
    commit failed 168 times while reporting nothing at all.

    Exits non-zero if anything needs attention, so it composes in a script.
    """
    from . import health as health_mod

    checks = health_mod.run_all()
    bad = [c for c in checks if c.bad]
    if not quiet_:
        console.print(health_mod.render(checks))
    elif bad:
        console.print(health_mod.render(checks))
    sys.exit(1 if bad else 0)


@main.command("drafts")
def drafts_cmd() -> None:
    """What happened to the drafts — the gate on unattended sending.

    Sent as written, rewritten, or deleted. That ratio decides when (and
    whether) this is allowed to send on its own; see
    docs/PLAN-becoming-a-chief-of-staff.md.
    """
    from .draft_outcomes import classify, render, summarise

    outcomes = classify()
    for o in outcomes:
        console.print(f"  [dim]{o.created[:16]}[/dim]  {o.state:16} {o.subject[:60]}")
    if outcomes:
        console.print()
    console.print(render(summarise(outcomes)))


@main.command("digest")
@click.option("--send", "do_send", is_flag=True, help="Deliver it to Telegram.")
@click.option("--to", default=None,
              help="Delivery target. Defaults to COS_DIGEST_TARGET.")
def digest_cmd(do_send: bool, to: str | None) -> None:
    """The daily summary. Prints by default; --send delivers it.

    Leads with anything broken, then your day. Assembled by code, not written
    by a model — a summary a model paraphrases can be wrong in ways you cannot
    see from the message.
    """
    from . import digest as digest_mod

    _require_setup()
    text = digest_mod.build()
    if not do_send:
        console.print(text)
        return
    target = to or digest_mod.default_target()
    ok, detail = digest_mod.send(text, to=target)
    if ok:
        console.print(f"[green]✓[/green] digest sent to {target}")
    else:
        console.print(f"[red]✗[/red] digest NOT sent: {detail}")
        sys.exit(1)


@main.command("alert")
@click.option("--dry-run", is_flag=True, help="Show what would be sent, send nothing.")
def alert_cmd(dry_run: bool) -> None:
    """Page Wei if something broke, at most once a day per problem.

    Meant to run from the 15-minute refresh. Alerts on the ok->broken
    transition only: an unguarded version would send 96 messages a day for one
    unfixed problem, and a muted bot is worse than no monitoring because it
    looks like coverage.
    """
    from . import alerting

    if dry_run:
        from . import health as health_mod

        decision = alerting.decide(health_mod.run_all())
        msg = alerting.format_alert(decision)
        console.print(msg or "[dim]nothing worth sending[/dim]")
        if decision.suppressed:
            console.print(f"[dim]({decision.suppressed} still-broken, within cooldown)[/dim]")
        return
    msg = alerting.run(send=True)
    if msg:
        console.print(msg)


@main.command("graph-people")
@click.option("--limit", default=0, help="Only the first N. 0 = all.")
@click.option("--apply", "apply_", is_flag=True, help="Actually write. Default is a dry run.")
def graph_people_cmd(limit: int, apply_: bool) -> None:
    """Step 1: create the person pages the links already point at.

    The brain holds 13,074 links and 8 person pages, because the mail importer
    writes `[[alex-doe|Alex Doe]]` and never creates the page. Every
    fact here comes from mail headers the importer already resolved; nothing is
    inferred, and an existing page is never overwritten.
    """
    from . import graphbuild

    res = graphbuild.build_people(limit=limit, dry_run=not apply_,
                                  log=lambda s: console.print(f"[dim]{s}[/dim]"))
    verb = "created" if apply_ else "would create"
    console.print(f"[green]✓[/green] {verb} {res.edges} page(s); "
                  f"{res.skipped} already existed."
                  + (f" [red]{res.errors} failed.[/red]" if res.errors else "")
                  + ("" if apply_ else "  Re-run with --apply to write."))


@main.command("graph-build")
@click.option("--limit", default=0, help="Only the first N entity pages. 0 = all.")
@click.option("--undo", is_flag=True, help="Remove the edges this wrote.")
def graph_build_cmd(limit: int, undo: bool) -> None:
    """Add the reverse edge gbrain's graph is missing.

    Every link in the brain runs email → person, so `graph people/x` has
    nothing to follow and multi-hop is unreachable. This writes the other
    direction, which opens up: person → their threads → the other people in
    them.

    Derived, idempotent, and disposable — `--undo` removes exactly what it
    wrote and leaves the wikilinks alone.
    """
    from . import graphbuild

    res = graphbuild.build(limit=limit, undo=undo,
                           log=lambda s: console.print(f"[dim]{s}[/dim]"))
    verb = "removed" if undo else "wrote"
    console.print(f"[green]✓[/green] {verb} {res.edges} edge(s) across "
                  f"{res.entities} entity page(s); {res.skipped} had no "
                  f"backlinks to reverse."
                  + (f" [red]{res.errors} failed.[/red]" if res.errors else ""))


@main.command("ms-auth")
def ms_auth_cmd() -> None:
    """Sign in to a Microsoft mailbox (Exchange Online / outlook.com).

    Prints a URL and a code; enter them in any browser. Needs
    COS_MS_CLIENT_ID in the environment or .env — the Application ID of a
    public-client app registered once in Entra with delegated
    Mail.ReadWrite, Calendars.Read, User.Read and offline_access.

    On a machine where Gmail is connected, this changes nothing: Gmail
    always wins backend selection. Sign in here only on the test machine.
    """
    from .config import Config
    from .ms_auth import MsAuthError, device_login

    cfg = Config.load()
    try:
        device_login(cfg.ms_client_id, log=console.print)
    except MsAuthError as e:
        console.print(f"[red]{e}[/red]")
        raise SystemExit(1) from e
    from .msgraph import profile

    who = profile()
    console.print(f"[green]Signed in as {who['address']}[/green]")


@main.command("ms-check")
def ms_check_cmd() -> None:
    """Prove the Microsoft connection end to end, read-only.

    Reads the profile, counts a week of mail, and lists today's calendar.
    Creates nothing.
    """
    from .msgraph import calendar, messages, profile

    who = profile()
    console.print(f"Mailbox: [bold]{who['address']}[/bold] ({who['name']})")
    msgs = messages(days=7, limit=200)
    console.print(f"Messages in the last 7 days: {len(msgs)}")
    for ev in calendar(days=1)[:5]:
        console.print(f"  {ev.get('start',{}).get('dateTime','')[:16]}  "
                      f"{ev.get('subject','')}")


@main.command("draft-auth")
def draft_auth_cmd() -> None:
    """Grant the one permission Kiran needs to leave you a draft.

    A separate Google consent from Kiran's own. Kiran's token is read-only and
    stays that way; this one lives in its own file and can be revoked on its
    own. Google has no draft-only scope — every scope that can create a draft
    can also send — so the guarantee that nothing gets sent is enforced by
    there being no send call in this codebase, not by the grant.
    """
    from .draft_broker import DRAFT_TOKEN_FILE, DraftError, authorize

    console.print("Opening Google's consent page. Approve for "
                  "[bold]you@yourcompany.com[/bold].")
    try:
        authorize(interactive=True)
    except DraftError as e:
        console.print(f"[red]✗[/red] {e}")
        sys.exit(1)
    except Exception as e:  # noqa: BLE001
        console.print(f"[red]✗[/red] {type(e).__name__}: {e}")
        sys.exit(1)
    console.print(f"[green]✓[/green] Saved to {DRAFT_TOKEN_FILE}.")
    console.print("Now run [bold]cos draft-test[/bold] to put a test draft in "
                  "your own Drafts folder.")


@main.command("draft-test")
@click.option("--body", default=None, help="Body text. A default is used if omitted.")
def draft_test_cmd(body: str | None) -> None:
    """Put a test draft addressed to you in your own Drafts folder.

    Proves the drafting path works without a real counterparty on the To line.
    The address is your mailbox's own, read from Gmail — not supplied here.
    """
    from .draft_broker import DraftError, create_self_draft

    text = body or (
        "This is a test draft.\n\n"
        "If you can read this in your Drafts folder, drafting works: "
        "Kiran can write a reply and leave it for you, and there is no code "
        "path anywhere in this system that can send it.\n\n"
        "Delete this draft when you are done — deleting is how you tell the "
        "system a draft was not good enough, and that ratio is what decides "
        "whether it is ever allowed to send on its own."
    )
    try:
        r = create_self_draft(text)
    except DraftError as e:
        console.print(f"[red]✗[/red] {e}")
        sys.exit(1)
    console.print(
        f"[green]✓[/green] Draft created in your Drafts folder\n"
        f"  to      {', '.join(r.to)}\n"
        f"  subject {r.subject}\n"
        f"  id      {r.draft_id}"
    )


@main.command("serve")
@click.option("--port", default=8787, show_default=True)
@click.option("--open", "open_browser", is_flag=True, help="Open it in your browser.")
def serve_cmd(port: int, open_browser: bool) -> None:
    """Dashboard and settings, reachable over Tailscale and nowhere else.

    Not the local network: an unauthenticated service already lives there, and
    this page decides who the assistant may email. Loopback and Tailscale's
    100.64.0.0/10 only; everything else gets 403.
    """
    from .webconfig import serve

    serve(port=port, open_browser=open_browser)


@main.command("snapshot")
def snapshot_cmd() -> None:
    """Compute the dashboard's numbers and cache them for the web page.

    Run by the 15-minute refresh. The page reads this file rather than
    recomputing: doing the work per request took over five minutes, because it
    rebuilds the whole ledger and calls Gmail.
    """
    from .webconfig import write_snapshot

    _require_setup()
    path = write_snapshot()
    console.print(f"[green]✓[/green] {path}")


@main.command("bench")
@click.option("--only", default="", help="Comma-separated question ids.")
@click.option("--label", default="", help="Name this run, e.g. 'baseline'.")
def bench_cmd(only: str, label: str) -> None:
    """Measure speed and accuracy against a fixed question set.

    Graded against facts drawn from the real data, not by a model — see
    docs/BENCHMARK.md for why, and for the question set.
    """
    from . import bench

    ids = [x.strip() for x in only.split(",") if x.strip()] or None
    result = bench.run(ids, label=label)
    path = bench.save(result)
    console.print()
    console.print(bench.render(result))
    console.print(f"[dim]{path}[/dim]")


@main.command("bench-report")
def bench_report_cmd() -> None:
    """Every benchmark run so far, so the movement is visible."""
    from . import bench

    console.print(bench.compare())
